# Generated by Django 4.0.6 on 2024-08-04 05:11

from django.db import migrations, models
import stocks.models
import stocks.validators
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('stocks', '0001_initial'), ('stocks', '0002_alter_stock_fisher1'), ('stocks', '0003_alter_stock_fisher1'), ('stocks', '0004_rename_fisher1_stock_fisher1_analysis'), ('stocks', '0005_stock_fisher1'), ('stocks', '0006_stock_fisher10_stock_fisher10_analysis_and_more'), ('stocks', '0007_alter_stock_fisher1_alter_stock_fisher10_and_more'), ('stocks', '0008_sipflatfile'), ('stocks', '0009_stock_psd_price'), ('stocks', '0010_alter_stock_fisher1_alter_stock_fisher11_and_more'), ('stocks', '0011_stock_eps_estimate_y10_analysis_alter_stock_fisher1'), ('stocks', '0012_stock_eps_estimate_y10'), ('stocks', '0013_stock_ee_eps_ey0'), ('stocks', '0014_stock_default_prediction'), ('stocks', '0015_alter_stock_default_prediction_and_more'), ('stocks', '0016_alter_stock_eps_estimate_y10_and_more'), ('stocks', '0017_sipflatfile_qt_pd_regression_summary'), ('stocks', '0018_rename_default_prediction_stock_qt_pd'), ('stocks', '0019_stock_conclusion_and_more'), ('stocks', '0020_alter_stock_eps_estimate_y10_analysis_and_more'), ('stocks', '0021_alter_stock_eps_estimate_y10_analysis_and_more'), ('stocks', '0022_rename_fisher10_analysis_stock_fisher10_completion_and_more'), ('stocks', '0023_rename_eps_estimate_y10_analysis_stock_eps_estimate_y10_completion'), ('stocks', '0024_stock_google_sheet_url')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIPFlatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=stocks.models.use_date_as_filename, validators=[stocks.validators.validate_parquet_file])),
                ('qt_pd_regression_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=7)),
                ('fisher1_completion', models.TextField(blank=True, null=True)),
                ('fisher1', models.BooleanField(blank=True, help_text='Does the company have products or services with sufﬁcient market potential to make possible a sizable increase in sales for at least several years?  In this analysis, consider factors like market share, international growth, and cross-selling opportunities?', null=True)),
                ('fisher10', models.BooleanField(blank=True, help_text='How good are the company’s cost analysis and accounting controls?', null=True)),
                ('fisher10_completion', models.TextField(blank=True, null=True)),
                ('fisher11', models.BooleanField(blank=True, help_text='Are there other aspects of the business, somewhat peculiar to the industry involved, which will give the investor important clues as to how outstanding the company may be in relation to its competition?', null=True)),
                ('fisher11_completion', models.TextField(blank=True, null=True)),
                ('fisher12', models.BooleanField(blank=True, help_text='Does the company have a short-range or long-range outlook in regard to profits?', null=True)),
                ('fisher12_completion', models.TextField(blank=True, null=True)),
                ('fisher13', models.BooleanField(blank=True, help_text='In the foreseeable future will the growth of the company require sufﬁcient equity ﬁnancing so that the larger number of shares then outstanding will largely cancel the existing stockholders’ beneﬁt from this anticipated growth?', null=True)),
                ('fisher13_completion', models.TextField(blank=True, null=True)),
                ('fisher14', models.BooleanField(blank=True, help_text='Does the management talk freely to investors about its affairs when things are going well but “clam up” when troubles and disappointments occur?', null=True)),
                ('fisher14_completion', models.TextField(blank=True, null=True)),
                ('fisher15', models.BooleanField(blank=True, help_text='Does the company have a management of unquestionable integrity?', null=True)),
                ('fisher15_completion', models.TextField(blank=True, null=True)),
                ('fisher2', models.BooleanField(blank=True, help_text='Does the management have a determination to continue to develop products or processes that will still further increase total sales potentials when the growth potentials of currently attractive product lines have largely been exploited?', null=True)),
                ('fisher2_completion', models.TextField(blank=True, null=True)),
                ('fisher3', models.BooleanField(blank=True, help_text='How effective are the company’s research and development efforts in relation to its size?', null=True)),
                ('fisher3_completion', models.TextField(blank=True, null=True)),
                ('fisher4', models.BooleanField(blank=True, help_text='Does the company have an above-average sales organization?', null=True)),
                ('fisher4_completion', models.TextField(blank=True, null=True)),
                ('fisher5', models.BooleanField(blank=True, help_text='Does the company have a worthwhile profit margin?', null=True)),
                ('fisher5_completion', models.TextField(blank=True, null=True)),
                ('fisher6', models.BooleanField(blank=True, help_text='What is the company doing to maintain or improve profit margins?', null=True)),
                ('fisher6_completion', models.TextField(blank=True, null=True)),
                ('fisher7', models.BooleanField(blank=True, help_text='Does the company have outstanding labor and personnel relations?', null=True)),
                ('fisher7_completion', models.TextField(blank=True, null=True)),
                ('fisher8', models.BooleanField(blank=True, help_text='Does the company have outstanding executive relations?', null=True)),
                ('fisher8_completion', models.TextField(blank=True, null=True)),
                ('fisher9', models.BooleanField(blank=True, help_text='Does the company have depth to its management?', null=True)),
                ('fisher9_completion', models.TextField(blank=True, null=True)),
                ('psd_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('eps_estimate_y10_completion', models.TextField(blank=True, null=True, verbose_name='LLM EPS Est Y10 Analysis')),
                ('eps_estimate_y10', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='LLM EPS Est Y10')),
                ('ee_eps_ey0', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='EPS Est Y0')),
                ('qt_pd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quant PD (%)')),
                ('conclusion', tinymce.models.HTMLField(blank=True, null=True)),
                ('google_sheet_url', models.URLField(null=True)),
            ],
        ),
    ]
