# Generated by Django 4.1 on 2024-06-24 21:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="fisher1",
            field=tinymce.models.HTMLField(default="I am not the eggman"),
        ),
    ]
