# Generated by Django 4.0.6 on 2024-08-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_squashed_0024_stock_google_sheet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='ee_eps_ey0',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='psd_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='qt_pd',
        ),
    ]
