# Generated by Django 4.0.6 on 2024-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_ee_eps_ey0_remove_stock_psd_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ci_company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
