# Generated by Django 4.1 on 2024-06-24 23:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_alter_stock_fisher1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="fisher1",
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
