# Generated by Django 4.1 on 2024-06-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_alter_stock_fisher1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock", old_name="fisher1", new_name="fisher1_analysis",
        ),
    ]
