# Generated by Django 4.1 on 2024-06-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_rename_fisher1_stock_fisher1_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="fisher1",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
