# Generated by Django 4.0.6 on 2024-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stock_ci_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='fisher1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher10',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher11',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher12',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher13',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher14',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher15',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher2',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher3',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher4',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher5',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher6',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher7',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher8',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher9',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
