# Generated by Django 4.1 on 2024-06-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_stock_fisher10_stock_fisher10_analysis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="fisher1",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have \nproducts or services with sufﬁcient market potential to make possible a \nsizable increase in sales for at least several years?  In this analysis, consider\nfactors like market share, international growth, and cross-selling opportunities.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher10",
            field=models.BooleanField(
                blank=True,
                help_text="How good are the company’s cost analysis and accounting controls?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher11",
            field=models.BooleanField(
                blank=True,
                help_text="Are there other aspects of the business, \nsomewhat peculiar to the industry involved, which will give the investor important \nclues as to how outstanding the company may be in relation to its competition?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher12",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have a short-range or long-range outlook in regard to profits?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher13",
            field=models.BooleanField(
                blank=True,
                help_text="In the foreseeable future will the \ngrowth of the company require sufﬁcient equity ﬁnancing so that the larger number \nof shares then outstanding will largely cancel the existing stockholders’ beneﬁt \nfrom this anticipated growth?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher14",
            field=models.BooleanField(
                blank=True,
                help_text="Does the management talk freely to investors \nabout its affairs when things are going well but “clam up” when troubles and disappointments occur?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher15",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have a management of unquestionable integrity?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher2",
            field=models.BooleanField(
                blank=True,
                help_text="Does the management have a \ndetermination to continue to develop products or processes that will still \nfurther increase total sales potentials when the growth potentials of currently \nattractive product lines have largely been exploited?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher3",
            field=models.BooleanField(
                blank=True,
                help_text="How effective are the company’s \nresearch and development efforts in relation to its size?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher4",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have an above-average sales organization?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher5",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have a worthwhile profit margin?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher6",
            field=models.BooleanField(
                blank=True,
                help_text="What is the company doing to maintain or improve profit margins?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher7",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have outstanding labor and personnel relations?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher8",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have outstanding executive relations?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher9",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have depth to its management?",
                null=True,
            ),
        ),
    ]
