# Generated by Django 4.0.6 on 2024-08-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_customfield_sipflatfile_custom_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sipflatfile',
            name='custom_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sip_flat_files', to='stocks.customfield'),
        ),
    ]
