# Generated by Django 4.0.6 on 2024-08-05 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_sipflatfile_custom_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipflatfile',
            name='qt_pd_regression_summary',
        ),
    ]
