# Generated by Django 4.1 on 2024-06-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_sipflatfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="psd_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
    ]
