# Generated by Django 4.0.6 on 2024-08-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_sipflatfile_qt_pd_regression_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipflatfile',
            name='custom_field',
        ),
        migrations.AddField(
            model_name='customfield',
            name='sip_flat_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.sipflatfile'),
        ),
    ]
