# Generated by Django 4.1 on 2024-06-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_stock_psd_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="fisher1",
            field=models.BooleanField(
                blank=True,
                help_text="Does the company have products or services with sufﬁcient market potential to make possible a sizable increase in sales for at least several years?  In this analysis, consider factors like market share, international growth, and cross-selling opportunities.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher11",
            field=models.BooleanField(
                blank=True,
                help_text="Are there other aspects of the business, somewhat peculiar to the industry involved, which will give the investor important clues as to how outstanding the company may be in relation to its competition?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher13",
            field=models.BooleanField(
                blank=True,
                help_text="In the foreseeable future will the growth of the company require sufﬁcient equity ﬁnancing so that the larger number of shares then outstanding will largely cancel the existing stockholders’ beneﬁt from this anticipated growth?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher14",
            field=models.BooleanField(
                blank=True,
                help_text="Does the management talk freely to investors about its affairs when things are going well but “clam up” when troubles and disappointments occur?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher2",
            field=models.BooleanField(
                blank=True,
                help_text="Does the management have a determination to continue to develop products or processes that will still further increase total sales potentials when the growth potentials of currently attractive product lines have largely been exploited?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fisher3",
            field=models.BooleanField(
                blank=True,
                help_text="How effective are the company’s research and development efforts in relation to its size?",
                null=True,
            ),
        ),
    ]
