# Generated by Django 4.0.6 on 2024-08-06 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_customfield_sip_flat_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='percentage_true',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
