# Generated by Django 4.0.6 on 2024-08-08 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_stock_percentage_true'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomField',
            new_name='CustomFieldScript',
        ),
    ]
