# Generated by Django 4.1 on 2024-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0011_stock_eps_estimate_y10_analysis_alter_stock_fisher1"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="eps_estimate_y10",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
