# Generated by Django 4.0.6 on 2024-08-08 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_rename_customfield_customfieldscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldscript',
            name='description',
        ),
        migrations.AlterField(
            model_name='customfieldscript',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('custom_field_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.customfieldscript')),
            ],
        ),
    ]
