# Generated by Django 4.1 on 2024-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0012_stock_eps_estimate_y10"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="ee_eps_ey0",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="EPS Est Y0",
            ),
        ),
    ]
