# Generated by Django 4.0.6 on 2024-08-08 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_remove_customfieldscript_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='sip_flat_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.sipflatfile'),
        ),
    ]
