# Generated by Django 4.1 on 2024-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0016_alter_stock_eps_estimate_y10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sipflatfile",
            name="qt_pd_regression_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
