# Generated by Django 4.0.6 on 2024-08-03 07:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_stock_conclusion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='eps_estimate_y10_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='LLM EPS Est Y10 Analysis'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher10_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher11_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher12_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher13_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher14_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher15_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher1_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher2_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher3_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher4_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher5_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher6_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher7_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher8_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fisher9_analysis',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
