# Generated by Django 4.0.6 on 2024-08-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_alter_stock_eps_estimate_y10_analysis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='fisher10_analysis',
            new_name='fisher10_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher11_analysis',
            new_name='fisher11_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher12_analysis',
            new_name='fisher12_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher13_analysis',
            new_name='fisher13_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher14_analysis',
            new_name='fisher14_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher15_analysis',
            new_name='fisher15_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher1_analysis',
            new_name='fisher1_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher2_analysis',
            new_name='fisher2_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher3_analysis',
            new_name='fisher3_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher4_analysis',
            new_name='fisher4_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher5_analysis',
            new_name='fisher5_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher6_analysis',
            new_name='fisher6_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher7_analysis',
            new_name='fisher7_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher8_analysis',
            new_name='fisher8_completion',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='fisher9_analysis',
            new_name='fisher9_completion',
        ),
    ]
