# Generated by Django 4.0.6 on 2024-08-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_rename_fisher10_analysis_stock_fisher10_completion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='eps_estimate_y10_analysis',
            new_name='eps_estimate_y10_completion',
        ),
    ]
