# Generated by Django 4.0.6 on 2024-08-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_rename_eps_estimate_y10_analysis_stock_eps_estimate_y10_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='google_sheet_url',
            field=models.URLField(null=True),
        ),
    ]
