# Generated by Django 4.1 on 2024-06-20 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Appraisal"),
                            (1, "Income Statement"),
                            (2, "Bank Statement"),
                        ],
                        default=0,
                    ),
                ),
                ("file", models.FileField(upload_to="media/")),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.DeleteModel(name="Example",),
        migrations.AddField(
            model_name="document",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="base_app.property"
            ),
        ),
    ]
