# Generated by Django 4.1 on 2024-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0002_document_property_delete_example_document_property"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
        migrations.AlterField(
            model_name="document", name="file", field=models.FileField(upload_to=""),
        ),
    ]
