# Generated by Django 4.1 on 2024-06-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_app", "0003_alter_property_options_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="pin",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
